server:
  port: 8080
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          cache-lifetime: 5
      routes:
        - id: user-service-public
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/auth/login/**, /api/v1/users/auth/refresh_token, /login/oauth2/code/google, /oauth2/authorization/google

        - id: user-service-protected
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: JwtAuthenticationFilter
              args: { }

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - JwtAuthenticationFilter

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - JwtAuthenticationFilter

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - JwtAuthenticationFilter