spring:
  jackson:
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  kafka:
    bootstrap-servers: kafka-service:29092
    schema-registry:
      url: http://schema-registry-service:8081

jwt:
  secret: giangnt2025randomasdawdakjcawnmawdawqerandomagainaweadawdasdawdawkanwdk
  expiration: 86400000
  refresh-token-expiration: 604800000
  token-prefix: Bearer
  header-string: Authorization

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - feign.RetryableException
          - feign.FeignException.ServiceUnavailable
          - java.net.ConnectException
  bulkhead:
    instances:
      productService:
        maxConcurrentCalls: 10
        maxWaitDuration: 500ms
  ratelimiter:
    instances:
      productService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans

kafka:
  topic:
    user-created: user-created-topic
    product-created: product-created-topic
    order-created: order-created-topic
    order-created-dlq: order-created-dlq
    payment-created: payment-created-topic