server:
  port: 3025

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://34.28.83.235:3306/order_db
    username: root
    password: giangnt_userdbD\ppv2/t/NEqdVlJ
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry:
      url: http://localhost:8081

feign:
  client:
    config:
      productServiceClient:
        retryer: feign.Retryer.NEVER_RETRY

kafka:
  consumer:
    order-group: order-group

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/