server:
  port: 3025

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://35.193.59.165:3306/order_db
    username: root
    password: giangnt@?Z?Ci31;Z(}6[kSq
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

feign:
  client:
    config:
      productServiceClient:
        retryer: feign.Retryer.NEVER_RETRY

kafka:
  consumer:
    order-group: order-group

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/