server:
  port: 4025

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://35.193.59.165:3306/payment_db
    username: root
    password: giangnt@?Z?Ci31;Z(}6[kSq
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry:
      url: http://localhost:8081
    streams:
      application-id: payment-streams-app

feign:
  client:
    config:
      productServiceClient:
        retryer: feign.Retryer.NEVER_RETRY

kafka:
  consumer:
    payment-group: payment-group

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/