server:
  port: 2025

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://35.193.59.165:3306/product_db
    username: root
    password: giangnt@?Z?Ci31;Z(}6[kSq
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

kafka:
  consumer:
    product-group: product-group
