server:
  port: 1025

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql_user:3306/user_db
    username: admin
    password: giangnt@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 707399821864-ur0e9oe8o5cgimv9q2smbggmi55s6gfb.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://api-gateway:8080/login/oauth2/code/google"
            scope: openid,profile,email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: sub
  kafka:
    bootstrap-servers: kafka:9092
    schema-registry:
      url: http://schema-registry:8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/