server:
  port: 3025

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3310/order_db
    username: admin
    password: giangnt@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

feign:
  client:
    config:
      productServiceClient:
        retryer: feign.Retryer.NEVER_RETRY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

resilience4j.circuitbreaker:
  instances:
    productService:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3

resilience4j.retry:
  instances:
    productService:
      maxAttempts: 3
      waitDuration: 2s
      retryExceptions:
        - feign.RetryableException
        - feign.FeignException.ServiceUnavailable
        - java.net.ConnectException

resilience4j.bulkhead:
  instances:
    productService:
      maxConcurrentCalls: 10
      maxWaitDuration: 500ms

resilience4j.ratelimiter:
  instances:
    productService:
      limitForPeriod: 10      # 10 requests per period
      limitRefreshPeriod: 1s  # period = 1 second
      timeoutDuration: 500ms

management.endpoints.web.exposure.include: "*"
