server:
  port: 2025

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3308/product_db
    username: admin
    password: giangnt@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

resilience4j.circuitbreaker:
  instances:
    userService:
      slidingWindowSize: 10          # number of recent requests considered
      failureRateThreshold: 50       # circuit opens if 50% requests fail
      waitDurationInOpenState: 10s   # circuit stays open for 10 seconds before retrying
      permittedNumberOfCallsInHalfOpenState: 3

management.endpoints.web.exposure.include: '*'
